### ISSUE TITLE
大佬，没有免安装版本吗？

### ISSUE THREAD

**Issue by drw2005** [maotoumao/MusicFreeDesktop#1]
来一个免安装版本吧！

**Comment by StrollStars** [comment]
同上，并且能够支持Win7。

**Comment by maotoumao** [comment]
免安装版本 是不是我给个zip就行了😂

**Comment by StrollStars** [comment]
@maotoumao 是的，只要解压就能运行的那种。

**Comment by StrollStars** [comment]
补充下，配置信息可以保存在程序所在目录，而不是放在用户目录或者注册表中，目前是前者。
这点可以参考下播放器MPC-BE。

**Comment by StrollStars** [comment]
@maotoumao 大佬可否兼容下Win7😂

**Comment by StrollStars** [comment]
@maotoumao 感谢大佬支持Win7，希望下一个版本能够出免安装版本😂
PS：配置文件能够放在程序所在目录。

**Comment by maotoumao** [comment]
> @maotoumao 感谢大佬支持Win7，希望下一个版本能够出免安装版本😂 PS：配置文件能够放在程序所在目录。

行 下个版本整一个

**Comment by maotoumao** [comment]
你本地node版本是多少呀？
看样子是node-sass的问题，看下这个能不能解决：https://www.cnblogs.com/breezefaith/p/17377532.html



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月08日 10:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [maotoumao/MusicFreeDesktop] 大佬，没有免安装版本吗？ (Issue #1) |

@maotoumao 感谢大佬支持Win7，希望下一个版本能够出免安装版本😂 PS：配置文件能够放在程序所在目录。

行 下个版本整一个

大佬 npm install报错怎么破

**Comment by maotoumao** [comment]
> > 你本地node版本是多少呀？ 看样子是node-sass的问题，看下这个能不能解决：https://www.cnblogs.com/breezefaith/p/17377532.html
> > […](#)
> > ---- 回复的原邮件 ---- | 发件人 | _**@**_._**> | | 日期 | 2023年09月08日 10:26 | | 收件人 | _**@**_.**_> | | 抄送至 | _**@**_._**>**_@_**.**_> | | 主题 | Re: [maotoumao/MusicFreeDesktop] 大佬，没有免安装版本吗？ (Issue #1) | @maotoumao 感谢大佬支持Win7，希望下一个版本能够出免安装版本😂 PS：配置文件能够放在程序所在目录。 行 下个版本整一个 大佬 npm install报错怎么破 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: _**@**_.***>
> 
> 16.13.1挺高了呀 难道说太高了？

看着报错和这个文档 https://www.cnblogs.com/breezefaith/p/17377532.html 里的一样，按这个文档先试试？

**Comment by drw2005** [comment]
【打包】新增 windows 免安装版、mac m1/m2版、linux版

大佬，哪个是免安装版本？
MusicFree-0.0.3-windows-setup.exe和MusicFree-0.0.3-windows-legacy-setup.exe都是安装版吧

**Comment by maotoumao** [comment]
> 【打包】新增 windows 免安装版、mac m1/m2版、linux版
> 
> 大佬，哪个是免安装版本？ MusicFree-0.0.3-windows-setup.exe和MusicFree-0.0.3-windows-legacy-setup.exe都是安装版吧

超过100M了没办法放蓝奏云。。。 
https://github.com/maotoumao/MusicFreeDesktop/actions/runs/7308123259

![image](https://github.com/maotoumao/MusicFreeDesktop/assets/31655147/5ad2eadc-5468-4054-b17d-4e69081238bf)

**Comment by drw2005** [comment]
> > 【打包】新增 windows 免安装版、mac m1/m2版、linux版
> > 大佬，哪个是免安装版本？ MusicFree-0.0.3-windows-setup.exe和MusicFree-0.0.3-windows-legacy-setup.exe都是安装版吧
> 
> 超过100M了没办法放蓝奏云。。。 https://github.com/maotoumao/MusicFreeDesktop/actions/runs/7308123259
> 
> ![image](https://private-user-images.githubusercontent.com/31655147/292746416-5ad2eadc-5468-4054-b17d-4e69081238bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NDk1NjAsIm5iZiI6MTcwMzU0OTI2MCwicGF0aCI6Ii8zMTY1NTE0Ny8yOTI3NDY0MTYtNWFkMmVhZGMtNTQ2OC00MDU0LWIxN2QtNGU2OTA4MTIzOGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDAwMDc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMDY5ZTUzMmZjZjNhZjE1YWFiMzlkNjY5MDhiNGJjMDdmYzI5ZjI3ZGM2N2Q0YjU4ZjQ3YjJkMTQ5NzllYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K6U_3-O2ihfVP_pNA8fCXiYo7xpT6P53LFsXjoFUytU)

是这里吗：https://wwzb.lanzoue.com/b042da1xe
里面好像没有你说portable版本
