### ISSUE TITLE
How to put in English?

### ISSUE THREAD

**Issue by peter9811** [maotoumao/MusicFreeDesktop#100]
Is possible a option to put the interface on English?

Thanks

**Comment by maotoumao** [comment]
Certainly, I'll do it in the next few weeks :)

**Comment by maotoumao** [comment]
That would be great! 
I'll set up the i18n first and then I'll let you know how to add languages.

Thank you for offering your help😀

**Comment by peter9811** [comment]
Perfect. I'll be happy to help

And I have a question, because I didn't really tried too much (language barrier): it's possible like take the library (the local one (already downloaded mp3)) and check if there is a better version and download it? If not could be possible implement it a future?

**Comment by maotoumao** [comment]
Good idea! 

There has not been such a feature so far, but I think it's better to provide a shortcut entry to search for the same song on different platforms, and let the users decide which result is better than the local one themselves.

---

And allow me to provide a bit more clarification. You can think of this software (MusicFree) as **a shell that only defines the framework of what a music player should have**. 

**MusicFree doesn't integrate any media resources**, instead, it abstracts the specifics of how to obtain music and how to search it into **plugins**, which are related to particular platforms. So in theory, you could play music from any platform you can search in the web by installing the appropriate plugins, and a plugin itself is just a simple commonjs module.

Therefore, I think that it's difficult to let the software decide which music quality is better, maybe it's better to leave the choice to users.

**Comment by peter9811** [comment]
Yes. I understand about the plugins, but I mean, for example if I have 128 kb/s and the software found a 320 kb/s from Netease and just download automatically all the "upgraded" version of the MP3 merging the metadata and all the stuff

Because, can be used like local player too?

**Comment by maotoumao** [comment]
Sorry for late reply. 

Got it, so it is expected that there would be an option for something like "auto upgrade local version", and the software should periodically check if there are better versions of local music available.

Is my understanding correct? 😄

**Comment by peter9811** [comment]
Something like that would be awesome
Thanks

**Comment by maotoumao** [comment]
Hi @peter9811, I've released a new version with i18n.
You can try the v0.0.4 [here](https://github.com/maotoumao/MusicFreeDesktop/releases/tag/v0.0.4).

English and Spanish were added with the help of ChatGPT, and feel free to correct me if there's any bad translation.

**Comment by peter9811** [comment]
@maotoumao
Sounds great. I'm going to work, when I come back I'll have a look into to check if everything is okay. Thanks
