### ISSUE TITLE
加载本地歌词文件

### ISSUE THREAD

**Issue by cgldimo** [maotoumao/MusicFreeDesktop#104]
有时在歌曲相同目录下保存了歌词，与歌曲文件名称相同
希望能够被识别和加载
![image](https://github.com/maotoumao/MusicFreeDesktop/assets/151028427/05b7cde9-7bd9-47d6-9c82-e8967929e942)

**Comment by maotoumao** [comment]
可 加了个规则识别同目录下的.lrc .LRC .txt文件 下个版本带上~

**Comment by thriken** [comment]
期待ing..
