### ISSUE TITLE
启动软件歌单会丢失

### ISSUE THREAD

**Issue by wuzhoumeng** [maotoumao/MusicFreeDesktop#126]
![Uploading Snipaste_2024-06-23_18-56-20.png…]()
软件每一次打开歌单都会丢失，只能通过Web DAV恢复，关掉软件歌单又会丢失

**Comment by maotoumao** [comment]
免安装版还是安装版呢？
图貌似挂了

**Comment by Ninian127** [comment]
4.0俩个版本都会如此，退回3.0就不会这样

**Comment by maotoumao** [comment]
> 4.0俩个版本都会如此，退回3.0就不会这样

get 是新安装的吗？我在免安装版上复现了

**Comment by Ninian127** [comment]
我一开始用的是4.0的安装包歌单会消失

**Comment by Ninian127** [comment]
后来又试了免安装的也消失了

**Comment by Ninian127** [comment]
我之前是没用过3.0和4.0版本的，是全新安装的

**Comment by Ninian127** [comment]
先安装3.0后再升级就不会出现歌单消失了

**Comment by wuzhoumeng** [comment]
对的，我在3.0的基础上升到4.0不会出现这个问题，后来重新下了4.0就出现歌单丢失，安装版是这样的，免安装的不清楚

**Comment by maotoumao** [comment]
是个bug，不好意思😓 昨天重新打了个包，今天晚上会重新发一个版本



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月25日 11:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [maotoumao/MusicFreeDesktop] 启动软件歌单会丢失 (Issue #126) |

对的，我在3.0的基础上升到4.0不会出现这个问题，后来重新下了4.0就出现歌单丢失，安装版是这样的，免安装的不清楚
