### ISSUE TITLE
能否导入别的平台的歌单？

### ISSUE THREAD

**Issue by Chenm4** [maotoumao/MusicFreeDesktop#13]
如题，希望能导入网易云或者qq音乐的歌单，这个功能好像有的软件能实现，不知道简不简单，感谢感谢~

**Comment by maotoumao** [comment]
导入歌单功能在【插件设置】这个tab里



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月12日 18:21 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFreeDesktop] 能否导入别的平台的歌单？ (Issue #13) |

如题，希望能导入网易云或者qq音乐的歌单，这个功能好像有的软件能实现，不知道简不简单，感谢感谢~

**Comment by Chenm4** [comment]
> 导入歌单功能在【插件设置】这个tab里
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年08月12日 18:21 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***> | | 主题 | [maotoumao/MusicFreeDesktop] 能否导入别的平台的歌单？ (Issue #13) | 如题，希望能导入网易云或者qq音乐的歌单，这个功能好像有的软件能实现，不知道简不简单，感谢感谢~ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

哦哦哦找到了找到了，感谢大佬感谢大佬！

**Comment by Chenm4** [comment]
但是好像这个只能导入非vip歌曲？是网易云的限制吗？我试了下导入的不全，少了一些vip歌曲

**Comment by Chenm4** [comment]
这个导入能实现导入vip歌曲吗，目前我看是无法实现

**Comment by maotoumao** [comment]
导入和播放的逻辑都在插件里，要导入和播放vip理论上改插件就行，但我不会也没精力搞破解😂
