### ISSUE TITLE
是否考虑接入 Navidrome 的API

### ISSUE THREAD

**Issue by 906051999** [maotoumao/MusicFreeDesktop#136]
- https://github.com/navidrome/navidrome
- 同样是开源软件
- 适合在个人服务端部署的音乐媒体后端
- 通过MusicFree强大的刮削能力
- 我认为这几乎是完美的方案

**Comment by thriken** [comment]
这个用插件就行吧

**Comment by 906051999** [comment]
> 这个用插件就行吧

唉呀，我好像忘记插件这东西了，我的

**Comment by 906051999** [comment]
已经找到了
{
      "name": "Navidrome",
      "url": "https://gitee.com/maotoumao/MusicFreePlugins/raw/v0.1/dist/navidrome/index.js",
      "version": "0.0.1"
    },
