### ISSUE TITLE
[建议]-本地歌曲导入标题应该取文件名

### ISSUE THREAD

**Issue by akFace** [maotoumao/MusicFreeDesktop#137]
#### 如图：在酷我下载的歌曲文件内置的名称全变成kuwo。我觉得应该直接取文件名当作标题即可
![image](https://github.com/maotoumao/MusicFreeDesktop/assets/22288837/592879ca-c4df-4348-882a-4fed3999bddb)

**Comment by maotoumao** [comment]
应该是这个音源的原始mp3文件内嵌的标题，作者和转移就是这些字符；
解决方案应该是下载时改一下tag，之后再优化一下吧🤔



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月02日 00:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFreeDesktop] [建议]-本地歌曲导入标题应该取文件名 (Issue #137) |

如图：在酷我下载的歌曲文件内置的名称全变成kuwo。我觉得应该直接取文件名当作标题即可

image.png (view on web)

**Comment by akFace** [comment]
> 应该是这个音源的原始mp3文件内嵌的标题，作者和转移就是这些字符； 解决方案应该是下载时改一下tag，之后再优化一下吧🤔
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年07月02日 00:00 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***> | | 主题 | [maotoumao/MusicFreeDesktop] [建议]-本地歌曲导入标题应该取文件名 (Issue #137) | 如图：在酷我下载的歌曲文件内置的名称全变成kuwo。我觉得应该直接取文件名当作标题即可 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

导入的时候直接取文件名作为标题就好啦

**Comment by maotoumao** [comment]
这里感觉还是要优先读取文件内嵌的内容的，如果读不到信息再用文件名；目前就是这样子的逻辑，先保持现状吧~ 
之后在下载的时候尝试写入文件的元信息就好了~
