### ISSUE TITLE
偶现歌曲加载失败

### ISSUE THREAD

**Issue by DearZack** [maotoumao/MusicFreeDesktop#15]
你好，加载失败后能否自动切换到下一首，现在是停了

**Comment by StrollStars** [comment]
![截图](https://github.com/maotoumao/MusicFreeDesktop/assets/10942225/aacefc50-955b-4a56-b1f9-3f8e1112e5b6)
如图设置应该就可以了，其实可以建议作者这个换成默认设置更符合使用习惯。

**Comment by maotoumao** [comment]
> ![截图](https://user-images.githubusercontent.com/10942225/262190677-aacefc50-955b-4a56-b1f9-3f8e1112e5b6.png) 如图设置应该就可以了，其实可以建议作者这个换成默认设置更符合使用习惯。 不过当前设置可能是作者考虑了，自动下一首可能有歌曲播放失败也不知道。

有道理，我把默认设置改掉
