### ISSUE TITLE
导入歌单无效

### ISSUE THREAD

**Issue by jifuqing** [maotoumao/MusicFreeDesktop#153]
![屏幕截图 2024-08-07 115118](https://github.com/user-attachments/assets/99a7963c-7975-45d9-8703-96a02ce7d8cd)
![屏幕截图 2024-08-07 115147](https://github.com/user-attachments/assets/a51cca49-7eac-4fc3-8dc9-73cee3771a89)
输完链接后显示为0首歌

**Comment by maotoumao** [comment]
插件问题，需要找这个插件的作者解决。。
