### ISSUE TITLE
mac m1 打不开app

### ISSUE THREAD

**Issue by kobeng** [maotoumao/MusicFreeDesktop#154]
<img width="278" alt="image" src="https://github.com/user-attachments/assets/6c25b2be-4e7f-4bf6-8a2b-ec083fb1fc4d">

**Comment by maotoumao** [comment]
看这里：https://musicfree.upup.fun/qa/pc.html#mac-m%E8%8A%AF%E7%89%87-%E6%8F%90%E7%A4%BA%E6%96%87%E4%BB%B6%E5%B7%B2%E6%8D%9F%E5%9D%8F
