### ISSUE TITLE
本地同名歌词加载后，无法同步播放，一直卡在最后一句

### ISSUE THREAD

**Issue by zhwchch** [maotoumao/MusicFreeDesktop#156]
本地已下载的歌词，能正确被加载到播放器，但是歌曲和歌词无法同步播放，歌词一直卡在最后一句，没有跟随播放

**Comment by maotoumao** [comment]
看下你的歌词是不是lrc格式的 里面的时间戳对不对



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月14日 00:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFreeDesktop] 本地同名歌词加载后，无法同步播放，一直卡在最后一句 (Issue #156) |

本地已下载的歌词，能正确被加载到播放器，但是歌曲和歌词无法同步播放，歌词一直卡在最后一句，没有跟随播放
