### ISSUE TITLE
为什么一打开音乐软件，火绒提示应用正在使用摄像头

### ISSUE THREAD

**Issue by chenyuncai** [maotoumao/MusicFreeDesktop#169]
摄像头相关功能调用是安全的吗

**Comment by optdesigns** [comment]
偷拍？一样弹窗 搞不懂音乐软件调取摄像头用来干啥

**Comment by chenyuncai** [comment]
> 偷拍？一样弹窗 搞不懂音乐软件调取摄像头用来干啥

应该不是，我打开好多网页都会提示，我怀疑还是有些api在申请某些权限被误伤了，我看了源码，没有media相关的代码
