### ISSUE TITLE
插件安装失败: Error invoking remote method 'install-plugin-local': AxiosError: Unsupported protocol d:

### ISSUE THREAD

**Issue by ZepEthan** [maotoumao/MusicFreeDesktop#17]
系统是win10专业版，软件安装无报错，插件安装的时候提示：
网络安装
安装失败: Errorinvoking remotemethod install-plugin-remote :AxiosError: timeout of 15000msexceeded
本地安装
安装失败: Error invoking remote method 'install-plugin-local': AxiosError: Unsupported protocol d:

**Comment by maotoumao** [comment]
安装本地文件写的有问题 下个版本改掉 
从网络安装是网络超时了 ，重新试一下
