### ISSUE TITLE
排行榜切换的时候，会出现排版异常

### ISSUE THREAD

**Issue by QuiryRain** [maotoumao/MusicFreeDesktop#171]
![recording](https://github.com/user-attachments/assets/0f6ee538-f142-45fe-b424-ab4d38107f95)

操作： 键盘左右键操作后会出现

**Comment by Wuziquan** [comment]
兄弟，排版的问题是小事，你能正常播放音乐吗？

**Comment by QuiryRain** [comment]
正常播放没问题

**Comment by Wuziquan** [comment]
QQ音乐的插件也正常？

**Comment by Wuziquan** [comment]
不对吧，现在应该有部分插件无法播放音乐了呀

**Comment by QuiryRain** [comment]
换了qq音乐的插件，确实不管播放
