### ISSUE TITLE
deepin linux桌面端安装插件失败，本地安装以及在线安装均报错

### ISSUE THREAD

**Issue by 1379441534** [maotoumao/MusicFreeDesktop#195]
![image](https://github.com/user-attachments/assets/71b2ff88-48ca-4174-8386-781c1faed537)
安装失败: Error invoking remote method 'install-plugin-local': Error: Request failed with status code 400

**Comment by maotoumao** [comment]
看样子是网络请求挂了，试试把对应的js文件下载到本地之后再安装呢
