### ISSUE TITLE
MusicFree启动时会访问摄像头

### ISSUE THREAD

**Issue by Minimalist-DIY** [maotoumao/MusicFreeDesktop#197]
MusicFree启动时被火绒阻止访问摄像头，为什么MusicFree会需要访问摄像头？
![火绒截图](https://github.com/user-attachments/assets/1ae2f5ae-5bcc-49cd-807f-c1d5439205e4)

**Comment by maotoumao** [comment]
代码里没有这样的逻辑，搜了下：
![image](https://github.com/user-attachments/assets/29797de4-4d1b-420e-872c-4424df0f888a)

不放心的话阻止摄像头权限就好了，不影响运行的
