### ISSUE TITLE
插件怎么调试呢

### ISSUE THREAD

**Issue by Q-Peppa** [maotoumao/MusicFreeDesktop#20]

**Comment by maotoumao** [comment]
如果要调试某个功能 直接nodejs环境下调用对应函数就行了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月31日 19:51 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [maotoumao/MusicFreeDesktop] 插件怎么调试呢 (Issue #20) |

Closed #20 as completed.
