### ISSUE TITLE
[bug] 软件没有正常关闭

### ISSUE THREAD

**Issue by dyfllll** [maotoumao/MusicFreeDesktop#200]
软件版本: 0.0.6
正常退出软件，任务管理器有进程残留，两个MusicFree.exe，开一次关一次就会增加一组
![PixPin_2024-12-26_10-54-51](https://github.com/user-attachments/assets/284ef286-fbe7-4f00-b377-145397ac04d5)
应该是request-forwarder.js没有正常退出
![PixPin_2024-12-26_10-58-45](https://github.com/user-attachments/assets/4afeda18-7eab-48a1-8afa-1321a5d42bb3)

**Comment by maotoumao** [comment]
谢谢反馈，我试试看 之前测试的时候没发现这个问题😂



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月26日 11:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFreeDesktop] [bug] 软件没有正常关闭 (Issue #200) |

软件版本: 0.0.6
正常退出软件，任务管理器有进程残留，两个MusicFree.exe，开一次关一次就会增加一组
PixPin_2024-12-26_10-54-51.jpg (view on web)
应该是request-forwarder.js没有正常退出
PixPin_2024-12-26_10-58-45.jpg (view on web)

**Comment by maotoumao** [comment]
没复现0.0，不过还是加了一些清理的代码

**Comment by dyfllll** [comment]
可能只在特殊环境下出现吧，只要清理了应该就没问题了
