### ISSUE TITLE
Mac版本任务栏图标太大

### ISSUE THREAD

**Issue by jwenjian** [maotoumao/MusicFreeDesktop#22]
如图：

<img width="1096" alt="image" src="https://github.com/maotoumao/MusicFreeDesktop/assets/25657798/aec2716e-24f7-4ed3-ab02-3ec232979b2e">

**Comment by showyoulove1990** [comment]
<img width="660" alt="image" src="https://github.com/maotoumao/MusicFreeDesktop/assets/29604166/15c0eae3-126f-430e-88c1-77d65ef692ef">
这个图标能换成一个透明背景的，个性化的图标就完美了
