### ISSUE TITLE
下载后识别乱码bug

### ISSUE THREAD

**Issue by xwshan** [maotoumao/MusicFreeDesktop#24]
### 软件中下载歌曲，使用本地音乐导入下载的歌曲显示乱码。

![image](https://github.com/maotoumao/MusicFreeDesktop/assets/43837345/986da162-34d8-4808-a21a-e22550332b27)

**Comment by maotoumao** [comment]
发一下原始文件吧～



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月15日 14:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFreeDesktop] 下载后识别乱码bug (Issue #24) |

软件中下载歌曲，使用本地音乐导入下载的歌曲显示乱码。

**Comment by xwshan** [comment]
### 这是MusicFree下载的mp3文件本地显示
![image](https://github.com/maotoumao/MusicFreeDesktop/assets/43837345/557577d4-25a2-4c76-bb21-9d09cde14db2)

**Comment by xwshan** [comment]
> 发一下原始文件吧～
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年09月15日 14:19 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***> | | 主题 | [maotoumao/MusicFreeDesktop] 下载后识别乱码bug (Issue #24) | 软件中下载歌曲，使用本地音乐导入下载的歌曲显示乱码。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

### 这是MusicFree下载的mp3文件本地显示
![image](https://github.com/maotoumao/MusicFreeDesktop/assets/43837345/557577d4-25a2-4c76-bb21-9d09cde14db2)

**Comment by maotoumao** [comment]
看来是源文件里面的信息就是乱码 我下载完之后没有额外写入音乐信息；先用可以读取音频内置信息的软件修改一下重新导入吧，我之后把这个加上
