### ISSUE TITLE
npm run package 的时候异常了

### ISSUE THREAD

**Issue by heyeah** [maotoumao/MusicFreeDesktop#27]
ERROR in ./src/renderer/pages/main-page/views/search-view/store/search-result.ts:24:14
TS2741: Property 'lyric' is missing in type '{ music: {}; album: {}; artist: {}; sheet: {}; }' but required in type 'ISearchResults<keyof SupportMediaItem>'.

**Comment by maotoumao** [comment]
开发版本加了个搜索歌词，没注意ts报错，重新拉一下代码吧~~
