### ISSUE TITLE
linux 编译打包之后执行点击关闭不能最小化

### ISSUE THREAD

**Issue by heyeah** [maotoumao/MusicFreeDesktop#28]
![录屏_选择区域_20231014224538](https://github.com/maotoumao/MusicFreeDesktop/assets/3827164/a5ffa5fc-7975-4d0e-903d-faa5deb737b7)

**Comment by maotoumao** [comment]
@zxp19821005 

wow～ 因为之前只顾着把功能写好，所以开发的流水线和规范啥的都没有很在意，直接在master分支提交的代码，也没在release页上新建个tag；目前master分支还有一些未开发完的功能，这确实不太好，最近打算完善一下；

### 自动更新

目前启动就提示更新是因为会自动把当前的版本（也就是**package.json**里的版本号）和 [项目仓库中的version](https://github.com/maotoumao/MusicFreeDesktop/blob/master/release/version.json) 做对比；

检测更新的逻辑在：[主渲染窗口useBootstrap函数](https://github.com/maotoumao/MusicFreeDesktop/blob/master/src/renderer/document/useBootstrap.ts)的45-47行；

具体检测更新的代码在[src/renderer/utils/check-update.ts](https://github.com/maotoumao/MusicFreeDesktop/blob/master/src/renderer/utils/check-update.ts)路径下，通过[ipc调用了主进程的函数](https://github.com/maotoumao/MusicFreeDesktop/blob/master/src/main/ipc/index.ts)；

如果要暂时避免弹出更新的话你可以把代码逻辑注释掉，或者把package.json里面的版本号修改为最新的版本号；


### 调试窗口

目前逻辑是做了判定，如果是开发模式会弹出调试窗口，如果是**已经打包好就不弹出**了，逻辑在：[40-45行](https://github.com/maotoumao/MusicFreeDesktop/blob/master/src/main/window/main-window.ts)；

我不知道是不是你对源代码做了些改动，或者打包方式有些差别导致判断失效，方便的话可以帮忙排查一下～ 


### linux 版本

下个版本把构建linux包的流水线加上；这个issue反馈的无法最小化的问题我在本地修掉了（忘了有没有push了，在改造窗口间通信机制，等改完了一起发）；


### 包路径

resources/res 应该是electron-forge自动把external资源拷贝到了resource目录；这里逻辑虽然能改但是和代码耦合，暂时先这样好了；


### 错误告警

开发的时候我一直忽略了这些报警，如果有影响开发体验的话直接在代码层面上关掉也好😂；最后一个问题感觉是devtools的问题，我好像也遇到过，但是貌似没啥影响所以没有深究
