### ISSUE TITLE
更新包发布建议

### ISSUE THREAD

**Issue by DoveBoy** [maotoumao/MusicFreeDesktop#29]
请求[musicfreedesktop](https://github.com/maotoumao/MusicFree/release) release更新包依旧在github release下发布，方便使用`scoop install` [musicfreedesktop](https://github.com/DoveBoy/Apps/raw/master/bucket/musicfreedesktop.json)进行安装升级管理。

**Comment by maotoumao** [comment]
可以的，命名上有什么规则限制嘛



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月17日 10:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFreeDesktop] 更新包发布建议 (Issue #29) |

请求musicfreedesktop release更新包依旧在github release下发布，方便使用scoop installmusicfreedesktop进行安装升级管理。

**Comment by DoveBoy** [comment]
> 可以的，命名上有什么规则限制嘛

没有的，按照当前命名就可以，建议命名尽量有体现特征的关键词标识，比如`windows`,`x64`,`arm64`等等。整个文件名类似`MusicFreeDesktop-windows-x64-$version.zip`，诸如此类都可以，方便匹配，感谢！
