### ISSUE TITLE
在下载管理这里 添加一个可以打开本地音乐文件夹功能

### ISSUE THREAD

**Issue by gonjudaren** [maotoumao/MusicFreeDesktop#30]
下载的音乐我都不知道在哪里  我还要自己去目录 去找 多麻烦   希望支持!!!

**Comment by maotoumao** [comment]
可以先在这里打开：设置-下载-下载目录-打开文件夹



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月18日 11:32 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFreeDesktop] 在下载管理这里 添加一个可以打开本地音乐文件夹功能 (Issue #30) |

下载的音乐我都不知道在哪里 我还要自己去目录 去找 多麻烦 希望支持!!!
