### ISSUE TITLE
Desktop版本增加“关联歌词”的建议~

### ISSUE THREAD

**Issue by beifenghu** [maotoumao/MusicFreeDesktop#31]
大佬膜拜！非常感谢佬的贡献，简直就是白嫖党的福音！
在这里提个小小的建议，手机版的上面有“关联歌词”，Desktop上面好像还莫有这个功能呢(是我不知道还是没找到哈哈)？希望优化或指导下！感谢~
![image](https://github.com/maotoumao/MusicFreeDesktop/assets/100113312/7f0e5460-e082-473f-bf0b-4d60dcbb1335)

**Comment by maotoumao** [comment]
PC版还没做~ 下个版本加上（大概等2-3周，这周末出去玩了啥都没写😂。。）
