### ISSUE TITLE
可以把lx music的收藏歌单导入吗

### ISSUE THREAD

**Issue by hyhwl** [maotoumao/MusicFreeDesktop#32]

**Comment by maotoumao** [comment]
不同软件的导入/导出规则不同，MusicFree倒是有导入/导出功能，只不过格式是软件内定义的（也就是MusicFree能识别的导入的数据只能是由MusicFree导出的数据）；

最近也看到了lx相关的一些事情，无意趁人之危；如果真的需要的话可以写个脚本把导入数据的格式转一下应该就好了（理论上，没仔细研究过），可以参考MusicFree的[备份相关的代码](https://github.com/maotoumao/MusicFree/blob/master/src/core/backup.ts)，无论直接转数据格式还是做成一个插件理论上都可以

**Comment by yoursinger** [comment]
作者大大好，最近在尝试这样的事。
但是lx默认导出的歌单数据（txt和csv格式）是不带链接的，而使用其lxmc格式则乱码无法识别，我只用歌名转换了对应的json但是导入后均无法播放，且软件也不能自己再进行搜索换源播放。
可以添加一个无法播放后自动搜索换源的逻辑吗？万分感谢。
