### ISSUE TITLE
更新v0.0.2——Bug

### ISSUE THREAD

**Issue by xwshan** [maotoumao/MusicFreeDesktop#39]
更新完v0.0.2，原来添加到我喜欢的歌单全没了。

**Comment by maotoumao** [comment]
不好意思，蓝奏云下载链接备注贴反了。。。orz

windows7/8/8.1下载文件名带legacy-setup的安装包；windows10/11下载setup.exe；两个版本数据可能会不互通，装串了就会出现这种情况。。。

**Comment by xwshan** [comment]
> 不好意思，蓝奏云下载链接备注贴反了。。。orz
> 
> windows7/8/8.1下载文件名带legacy-setup的安装包；windows10/11下载setup.exe；两个版本数据可能会不互通，装串了就会出现这种情况。。。

还能拯救吗？
或者只能重新一个个添加 ☺O(∩_∩)O哈哈~

**Comment by maotoumao** [comment]
只能重新加😂😂😂 实在不好意思 orz

如果是win10/11还是下不带legacy的吧 体验可能会好一点😉



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月07日 13:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [maotoumao/MusicFreeDesktop] 更新v0.0.2——Bug (Issue #39) |

不好意思，蓝奏云下载链接备注贴反了。。。orz

windows7/8/8.1下载文件名带legacy-setup的安装包；windows10/11下载setup.exe；两个版本数据可能会不互通，装串了就会出现这种情况。。。

还能拯救吗？
或者只能重新一个个添加 ☺O(∩_∩)O哈哈~

**Comment by xwshan** [comment]
> 只能重新加😂😂😂 实在不好意思 orz 如果是win10/11还是下不带legacy的吧 体验可能会好一点😉
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年11月07日 13:08 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>、State ***@***.***> | | 主题 | Re: [maotoumao/MusicFreeDesktop] 更新v0.0.2——Bug (Issue #39) | 不好意思，蓝奏云下载链接备注贴反了。。。orz windows7/8/8.1下载文件名带legacy-setup的安装包；windows10/11下载setup.exe；两个版本数据可能会不互通，装串了就会出现这种情况。。。 还能拯救吗？ 或者只能重新一个个添加 ☺O(∩_∩)O哈哈~ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

OK哈😂😂😂
