### ISSUE TITLE
陷入本地音乐扫描死循环

### ISSUE THREAD

**Issue by Zhou-Jiangcheng** [maotoumao/MusicFreeDesktop#40]
添加本地音乐自动扫描文件夹后，陷入死循环，不停从头到尾扫描目录，无法播放。

![截图 2023-11-07 11-34-37](https://github.com/maotoumao/MusicFreeDesktop/assets/39516706/6185c777-62ac-45e5-991b-49d8f239ade8)

[录屏 2023-11-07 11-36-16.webm](https://github.com/maotoumao/MusicFreeDesktop/assets/39516706/7b9d2bbf-418b-42d6-928e-6185773b165d)

**Comment by Zhou-Jiangcheng** [comment]
![截图 2023-11-07 11-38-07](https://github.com/maotoumao/MusicFreeDesktop/assets/39516706/8500f094-42ba-47b2-8efe-c5573afb0787)

**Comment by Zhou-Jiangcheng** [comment]
debian 12
Musicfree 0.0.2

**Comment by maotoumao** [comment]
感谢反馈～ 设置里面有一个「播放失败时」的设置，把它设置成”暂停“就不会死循环了； 

![image](https://github.com/maotoumao/MusicFreeDesktop/assets/31655147/095eb6a9-9a37-4daf-9cfd-1779426621f3)


问题的出现原因应该是本地文件播放失败了，大概是播放时的路径不对，我回去看下～
