### ISSUE TITLE
歌词显示问题

### ISSUE THREAD

**Issue by zangqiourun** [maotoumao/MusicFreeDesktop#46]
搜索并关联歌词后，不显示歌词

![image](https://github.com/maotoumao/MusicFreeDesktop/assets/130052096/c1796fec-51e2-4be6-b301-344adf760dc5)
![image](https://github.com/maotoumao/MusicFreeDesktop/assets/130052096/abb266db-87e3-427f-8358-bbc154fdd6ac)

**Comment by zangqiourun** [comment]
应该是部分歌曲会这样

**Comment by maotoumao** [comment]
换一首歌关联吧😂
可能目标歌曲也没歌词，就会出现这种情况，我想想看怎么给个提示



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月10日 17:14 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFreeDesktop] 歌词显示问题 (Issue #46) |

搜索并关联歌词后，不显示歌词

**Comment by zangqiourun** [comment]
> 换一首歌关联吧😂 可能目标歌曲也没歌词，就会出现这种情况，我想想看怎么给个提示
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年11月10日 17:14 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***> | | 主题 | [maotoumao/MusicFreeDesktop] 歌词显示问题 (Issue #46) | 搜索并关联歌词后，不显示歌词 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

提示关联成功了，换了几个源都是这样，可能真的目标歌曲也没歌词吧。不过换了QQ音乐的歌曲源后自动关联了。应该不是BUG。这个issue可以忽略关闭了：）
