### ISSUE TITLE
右键点击下载的歌曲所在文件夹报错

### ISSUE THREAD

**Issue by Colin07** [maotoumao/MusicFreeDesktop#49]
![1](https://github.com/maotoumao/MusicFreeDesktop/assets/30275465/34e1f3c3-f69c-428b-bdfe-bd1fc0105de7)
![2](https://github.com/maotoumao/MusicFreeDesktop/assets/30275465/fc8f1160-509d-442b-9233-dba25295aa4d)

**Comment by maotoumao** [comment]
这个是在0.0.1版本下载的嘛？还是新版本下载之后右键打开一定会出现呀



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月18日 08:41 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFreeDesktop] 右键点击下载的歌曲所在文件夹报错 (Issue #49) |

**Comment by Colin07** [comment]
0.0.2版本的，右键必报错，麻烦大佬看下

**Comment by maotoumao** [comment]
ok～ 看截图不像windows，是mac嘛？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月18日 08:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [maotoumao/MusicFreeDesktop] 右键点击下载的歌曲所在文件夹报错 (Issue #49) |

0.0.2版本的，右键必报错，麻烦大佬看下

**Comment by Colin07** [comment]
是windows版本的

**Comment by maotoumao** [comment]
ok～我看看



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月18日 08:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [maotoumao/MusicFreeDesktop] 右键点击下载的歌曲所在文件夹报错 (Issue #49) |

是windows版本的

**Comment by maotoumao** [comment]
应该是下载之后不能立刻打开文件夹，重启之后就能打开吧～ 大概定位到问题了
