### ISSUE TITLE
导入插件一直失败！

### ISSUE THREAD

**Issue by A-little-bit-of-data** [maotoumao/MusicFreeDesktop#5]
通过网络安装报下面两个错
导入GitHub的
![image](https://github.com/maotoumao/MusicFreeDesktop/assets/31812278/49d5eaaa-907f-44e2-990f-814b13d03653)
导入gitee的
![image](https://github.com/maotoumao/MusicFreeDesktop/assets/31812278/8e14c89f-cd7a-467c-9f32-2451798c9c1f)

把这个json下载下来本地导入报下面的错
![image](https://github.com/maotoumao/MusicFreeDesktop/assets/31812278/151cfedb-a882-4812-a7ca-4f4149139c29)

**Comment by maotoumao** [comment]
本地导入json是bug。。。我修掉了
导入github的应该是被墙了，15秒自动超时了；
导入gitee的你输入的是啥链接呀？这个没复现
