### ISSUE TITLE
[FEATURE] 增加代理功能

### ISSUE THREAD

**Issue by zhtok** [maotoumao/MusicFreeDesktop#51]
**注意事项**
- [x] 确保已经阅读过ReadMe并*了解本软件的定位*
- [x] 确保你的新需求/想法合理合法，且*不是因为无解决方案的众口难调导致的个例问题*

------

**需求描述**
单位电脑需要使用HTTP代理（带用户名密码验证）才能访问互联网，MusicFree目前没有该功能，在这种情况下MusicFree无法访问网络，建议程序里内置代理功能。

**替代方案**
无

**其他信息**
无

**Comment by xxnuo** [comment]
<img width="580" alt="Image" src="https://github.com/user-attachments/assets/3c93afdb-1825-4c58-b2f5-adc07fbd1a05" />

代理功能不生效，本地对应端口已起 HTTP SOCKS 代理服务器

**Comment by ciallothu** [comment]
确实，只是个样子
