### ISSUE TITLE
当歌曲名称很长的时候，右键点击图标出现的窗口很长

### ISSUE THREAD

**Issue by Colin07** [maotoumao/MusicFreeDesktop#59]
windows版本下，当歌曲名称很长的时候，右键点击左下角图标时候，弹出的窗口长度跟歌曲名称长度一样长，有时会占了整个桌面，建议设置最大长度，超过长度就隐藏
<img width="618" alt="bug" src="https://github.com/maotoumao/MusicFreeDesktop/assets/30275465/61940437-5ba5-4f08-9be4-e082b0c26f21">

**Comment by maotoumao** [comment]
ok~ 确实不好看 我改下
