### ISSUE TITLE
哔哩哔哩中的一点bug

### ISSUE THREAD

**Issue by Halecoder** [maotoumao/MusicFreeDesktop#6]
![image](https://github.com/maotoumao/MusicFreeDesktop/assets/75030331/7a34327a-43e0-4b4a-a4ef-13ecfe087e43)

时长只是一首歌的时间

**Comment by Halecoder** [comment]
这个应该找插件作者？还是

**Comment by maotoumao** [comment]
数据都是插件提供的，所以issue应该提在这里：https://github.com/maotoumao/MusicFreePlugins
不过暂时修不掉，因为b站分p视频没有直接提供第一p的时长，只给了个总时长。。。不影响播放，实际播放的时候显示的还是真实的时间；
如果想要查看完整的分p视频，可以去专辑tab下找同名条目，里面信息是正确的
