### ISSUE TITLE
插件管理无法对插件进行排序

### ISSUE THREAD

**Issue by mcp2016** [maotoumao/MusicFreeDesktop#64]
插件管理无法对插件进行排序

**Comment by maotoumao** [comment]
下个版本加上



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月14日 16:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFreeDesktop] 插件管理无法对插件进行排序 (Issue #64) |

插件管理无法对插件进行排序
