### ISSUE TITLE
Windows下发布者信息乱码

### ISSUE THREAD

**Issue by 2yl6hvuxm** [maotoumao/MusicFreeDesktop#74]
Windows下安装完成后，控制面板程序列表中软件发布者显示乱码“çŒ«å¤´çŒ«“，应该是UTF-8的”猫头猫“吧

**Comment by maotoumao** [comment]
0.0一直没注意。。。确实😂😂😂



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月29日 16:40 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFreeDesktop] Windows下发布者信息乱码 (Issue #74) |

Windows下安装完成后，控制面板程序列表中软件发布者显示乱码“çŒ«å¤´çŒ«“，应该是UTF-8的”猫头猫“吧

**Comment by 2yl6hvuxm** [comment]
强迫症扫了一眼之后感觉太难受了去注册表手动改了🤣

> 0.0一直没注意。。。确实😂😂😂
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年12月29日 16:40 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***> | | 主题 | [maotoumao/MusicFreeDesktop] Windows下发布者信息乱码 (Issue #74) | Windows下安装完成后，控制面板程序列表中软件发布者显示乱码“çŒ«å¤´çŒ«“，应该是UTF-8的”猫头猫“吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by 2yl6hvuxm** [comment]
> 0.0一直没注意。。。确实😂😂😂
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年12月29日 16:40 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***> | | 主题 | [maotoumao/MusicFreeDesktop] Windows下发布者信息乱码 (Issue #74) | Windows下安装完成后，控制面板程序列表中软件发布者显示乱码“çŒ«å¤´çŒ«“，应该是UTF-8的”猫头猫“吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

强迫症扫了一眼之后感觉好难受，去注册表里面手动改了🤣

**Comment by maotoumao** [comment]
改成拼音了 😆 
![image](https://github.com/maotoumao/MusicFreeDesktop/assets/31655147/cf00ac83-7b4f-450e-b62e-8a660ad40c38)
