### ISSUE TITLE
Mp3格式内嵌歌词无法识别

### ISSUE THREAD

**Issue by fringesy** [maotoumao/MusicFreeDesktop#79]
mp3格式的歌曲内嵌的歌词无法显示，flac格式的可以

**Comment by maotoumao** [comment]
给个无法识别的文件我试一下吧～



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月08日 10:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFreeDesktop] Mp3格式内嵌歌词无法识别 (Issue #79) |

mp3格式的歌曲内嵌的歌词无法显示，flac格式的可以

**Comment by fringesy** [comment]
> 给个无法识别的文件我试一下吧～
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年01月08日 10:39 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***> | | 主题 | [maotoumao/MusicFreeDesktop] Mp3格式内嵌歌词无法识别 (Issue #79) | mp3格式的歌曲内嵌的歌词无法显示，flac格式的可以 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

无法识别内嵌歌词的mp3文件，刚才在其他播放器测试了可以识别出来。
[https://github.com/fringesy/testmp3/blob/main/%E7%8E%84%E8%A7%9E%20-%20%E6%88%8F%E8%AF%AD%E8%8A%B1.mp3](url)

**Comment by maotoumao** [comment]
修好啦
