### ISSUE TITLE
拔掉耳机就会公放，希望加上拔掉耳机暂停的功能

### ISSUE THREAD

**Issue by uchaoxi** [maotoumao/MusicFreeDesktop#83]
场景就是在公司边听歌边干活，然后拔掉耳机准备去开会，结果直接变成公放了，使社恐感觉到十分尴尬

**Comment by maotoumao** [comment]
😂😂😂没问题 下版本加上



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月16日 17:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFreeDesktop] 拔掉耳机就会公放，希望加上拔掉耳机暂停的功能 (Issue #83) |

场景就是在公司边听歌边干活，然后拔掉耳机准备去开会，结果直接变成公放了，使社恐感觉到十分尴尬
