### ISSUE TITLE
MacBookM1 歌词显示问题反馈

### ISSUE THREAD

**Issue by cat-sir** [maotoumao/MusicFreeDesktop#87]
大佬你好。
MacBookM1 当前版本0.03，在使用桌面歌词的时候。
歌词的换行（或者说是下一句）有时候会出现叠影？？或者其他形容方式，影响看歌词，不知道是不是我个人的问题，或者说有其他朋友使用过程也有遇到这个问题。
<img width="920" alt="1" src="https://github.com/maotoumao/MusicFreeDesktop/assets/71893945/471b8ab4-280b-40dd-ba5b-ffaa0bbde60b">
<img width="920" alt="2" src="https://github.com/maotoumao/MusicFreeDesktop/assets/71893945/3d62fc2f-9784-49c1-9027-7241f27cb575">

**Comment by maotoumao** [comment]
看来是个普遍问题，下个版本尝试修复~ https://github.com/electron/electron/pull/32452
