### ISSUE TITLE
[FEATURE] release中能否为windows提供portable免安装版本

### ISSUE THREAD

**Issue by karma-sun** [maotoumao/MusicFreeDesktop#89]
**注意事项**
- [ ] 确保已经阅读过ReadMe并*了解本软件的定位*
- [ ] 确保你的新需求/想法合理合法，且*不是因为无解决方案的众口难调导致的个例问题*

------

**需求描述**
release中能否为windows提供portable免安装版本

**替代方案**

**Comment by GiveStar** [comment]
同求

**Comment by maotoumao** [comment]
ok
